config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :passwords => 'passwords', confirmations: 'confirmations', sessions: "sessions"  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    root to: "devise/sessions#new"
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        member do
          put :update_password
          put :update_user_skills
          get :get_user_services
          get :get_user_availed_services
          post :add_working_days
          get :get_user_events
          put :add_stripe_token
          get :recent_payouts
          get :total_earning
          post :payout
          get :get_bank_info
          get :get_unreviewed_events
          get :user_event_reviews
          post :contact_as
          get :visitors
          get :notifications
          put :update_notification
          get :fetch_notifications
          get :vouchers
          get :verify_voucher
        end
        collection do
          put :forgot_password
          post :facebook_auth
          get :get_skilled_data
          get :search
        end
      end
      resources :sessions
      resources :service_categories
      resources :comments
      resources :appointments
      resources :endorsements do
        collection do
          put :un_endorse
        end
      end
      resources :user_connections do
        collection do
          get :get_connection_requests
          get :get_all_my_approved_connection_list
          get :get_connection_requests_new
          put :remove_connection
          get :connection_requests
        end
      end
      resources :working_days
      resources :reviews
      resources :services do
        member do
          get :check_available_slots_on
          get :service_reviews
        end
        collection do
          get :search
        end
      end
      resources :posts do
        member do
          post :like_post
          put  :share_post
          put  :repost
          get  :post_reactions
          post  :report_post
        end
        collection do

        end
      end
      resources :events do
        collection do
          get :search
        end
        member do
          get :get_attendees
          get :event_reviews
          post :charge_event
        end
      end
      resources :saved_events, only: [:create, :index] do
        collection do
          post :unsave
          get :services
        end
      end
      resources :tickets, only: [:index, :create, :show, :update]
      resources :messages, only: :create
      resources :chats, only: [:create, :index]
    end
  end

  resources :users
  resources :offers
  resources :home do
    collection do
      get :user_after_confirmation
      post :users_report
      post :posts_report
      post :services_report
      get :chat_room
    end
  end
  resources :categories
  resources :skills
  resources :sub_skills
  resources :events do
    collection do
      get :register
      get :preview
    end
  end
  resources :appointments
  resources :services do
    collection do
      get :preview
    end
  end
  resources :payments
  resources :outgoing_payments
  resources :charges do
    collection do
      post :charge_new_user_for_event
      get  :validate_tickets_count
    end
  end
  resources :posts
  resources :report_posts
  get  "registration" => "charges#registration"

  get '*path' => 'home#handle_no_rout'

  # mount ActionCable.server => '/cable'
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApplicationController

  # skip_before_action :verify_authenticity_token

  before_action :verify_api_token#, except: [:create]
  before_action :find_user, only: [:charge_event]
  before_action :set_event, only: [:show, :update, :destroy, :get_attendees, :charge_event, :event_reviews]

  # GET /events
  def index
    @events = Event.where(search_condition(Event))
    render json: @events, include: :ticket_packages, user_id: @current_user

  end

  # GET /events/1
  def show
    render json: @event, include: [:ticket_packages], user_id: @current_user
  end

  # POST /events
  def create
    # byebug
    @event = Event.new(event_params)
    @event.start_date = params[:event][:start_date].gsub("  ", " +")
    @event.end_date = params[:event][:end_date].gsub("  ", " +")
    
    if @event.save
      if @event.is_free_event
        user = @event.owner.update(free_events: @event.owner.free_events-1)
      end
      # tokens =  UserDevice.joins(:user).active.where.not("users.is_upcoming_events = ?", "false").pluck(:push_token)
      # ids = UserDevice.joins(:user).active.where.not("users.is_upcoming_events = ?", "false").pluck(:user_id)
      # if tokens.present?
      #   FcmPush.new.send_push_notification('',"#{@event.owner.first_name} post upcoming event",tokens)
      #   Notification.import_record(ids, @event)
      # end
      render json: @event, include: [:ticket_packages], user_id: @current_user
    else
      render :json => {:error => "Unable to create event at this time.", error_log: @event.errors.full_messages}, :status => :unprocessable_entity
    end
  end

  # PATCH/PUT /events/1
  def update
    p_ticket_packages = @event.ticket_packages.ids
    tmp_id = @event.id.to_s + '000000'
    @event.ticket_packages.update_all(event_id: tmp_id.to_i )
    if @event.update(event_params)

      tokens =  UserDevice.joins(:user).active.where.not("users.is_upcoming_events = ?", "false").pluck(:push_token)
      ids = UserDevice.joins(:user).active.where.not("users.is_upcoming_events = ?", "false").pluck(:user_id)
      if tokens.present?
        FcmPush.new.send_push_notification('',"#{@event.owner.first_name} post upcoming event",tokens)
        Notification.import_record(ids, @event)
      end
      
      # tokens =  UserDevice.joins(:user).active.where.not("users.is_event_details = ?", "false").pluck(:push_token)
      # if tokens.present?
      #   FcmPush.new.send_push_notification('',"#{@event.owner.first_name} changed details for an event",tokens)
      #   ids = UserDevice.joins(:user).active.where.not("users.is_event_details = ?", "false").pluck(:user_id)
      #   Notification.import_update(ids, @event)
      # end 
      @event.start_date = params[:event][:start_date].gsub("  ", " +")
      @event.end_date = params[:event][:end_date].gsub("  ", " +")
      @event.save!

      TicketPackage.where("id IN(?)", p_ticket_packages).destroy_all
      @event.reload
      render json: @event, include: [:ticket_packages], user_id: @current_user
    else
      WorkingDay.where("id IN(?)", p_ticket_packages).update_all(event_id: @event.id)
      render :json => {:error => "Unable to update record this time. Please try again later.", error_log: @event.errors.full_messages}, :status => :unprocessable_entity
    end

    # if @event.update(event_params)
    #   render json: @event, include: [:ticket_packages]
    # else
    #   render :json => {:error => "Unable to update record this time. Please try again later.", error_log: @event.errors.full_messages}, :status => :unprocessable_entity
    # end
  end

  # DELETE /events/1
  def destroy
    event = @event
    if @event.destroy
      # tokens =  UserDevice.active.pluck(:push_token)
      # FcmPush.new.send_push_notification('',"#{event.owner.first_name} created new event",tokens) if tokens.present?
      render :json => {:success => "Event deleted successfully"}, :status => :ok
    else
      render :json => {:error => "Unable to delete event at this time.", error_log: @event.errors.full_messages}, :status => :unprocessable_entity
    end

  end

  def event_earning

  end

  def get_attendees

    begin
      # render json: @event, include: {tickets: {include: :owner}}
      tickets = @event.tickets
      users = User.where("id IN(?)",tickets.pluck(:owner_id).uniq)
      attandies ={}
      gateway_charges = 0.0
      my_users=[]
      users.each do |user|
        total_price = 0.0
        us = user.serializable_hash
        ticket_pckgs = user.tickets.where(event_id:@event.id).group_by(&:ticket_package_id)
        tp=[]
        ticket_pckgs.each do |pckg|
          p = TicketPackage.find(pckg.first)
          tp.push({title: p.ticket_type, scanned_count: pckg.last.count{|app| app.has_scanned == true}, tickets: pckg.last.count, price: p.price, ticket_ids: pckg.last.map(&:id)})
          total_price += (pckg.last.count* p.price.to_f).to_f
        end
        us[:packages] = tp
        us[:total_price]= total_price
        us[:gateway_charges]= gateway_charges
        my_users.push(us)
      end
      render json: my_users#, include: {tickets: {include: :owner}}
    rescue
      render :json => {:error => "Unable to get attendies at this time, try again later."}, :status => :unprocessable_entity
    end

  end

  def event_reviews
    render json: @event, include: {reviews: {include: [:user]}}
  end

  def search
    begin
      options = {
          # keyword: params[:keyword],
          latitude: params[:latitude],
          longitude: params[:longitude],
          distance: params[:distance].to_i,
          title: params[:title],
          min_price: params[:min_price],
          from_date: params[:from_date],
          to_date: params[:to_date],
      }
      events = Event.search(options)
      render json: events, include: [:ticket_packages], user_id: @current_user
    rescue
      render :json => {:error => "Unable to search events at this time, try again later."}, :status => :unprocessable_entity
    end
  end


  def save_user_event
    begin
      if params[:save] == "1"
        SavedEvent.create(user_id: params[:user_id], event_id: params[:event_id])
        msg= "saved"
      else
        SavedEvent.where(user_id: params[:user_id], event_id: params[:event_id]).destroy_all
        msg= "unsaved"
      end
      render :json => {:success => "Event has #{msg} successfully"}, :status => :ok
    rescue
      render :json => {:error => "Unable to save/unsave event at this time"}, :status => :unprocessable_entity
    end
  end

  def charge_event
    response = StripeCustomer.new(@user, params[:amount], @event, params).charge
    if response
    render :json => {:success => "Charge has been created successfully"}, :status => 200
    else
      render :json => {:error => "Something went wrong"}, :status => :unprocessable_entity
    end

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    begin
      @event = Event.find(params[:id])
    rescue
      render :json => {:error => "Event not found with provided id"}, :status => 404
    end
  end

  def find_user
    begin
      @user =  User.find(params[:liked_by_id] || params[:user_id])
      render :json => {:error => "User is not activated. Please check your email #{@user.email} for user activation."} unless @user.is_confirmed
    rescue
      render :json => {:error => "User not found with provided id"}, :status => 404
    end
  end

  # Only allow a trusted parameter “white list” through.
  def event_params
    params.require(:event).permit(:is_free_event, :is_tax_by_creator, :video_url, :latitude, :longitude, :address, :dress_code, :speaker, :start_date, :end_date, :title, :description, :status, :is_paid, :price, :owner_id, :cover_image, :has_published, :is_recurring, :recurring_type, :is_enabled, :max_tickets, ticket_packages_attributes: [:ticket_type, :price, :maximum_tickets])
  end

  def verify_api_token
    return true if authenticate_token
    render json: { errors: "Access denied" }, status: 401
  end

  def authenticate_token
    return false if params[:api_token].blank?
    @current_user = User.find_by(api_token: params[:api_token])
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:register, :preview]

  before_action :set_event, only: [:show, :edit, :update, :destroy, :register, :preview]
  layout 'home', except: [:register, :preview]
  # GET /events
  # GET /events.json
  def index
    if params[:user_id]
      @user = User.find_by_id(params[:user_id])
      @events = Event.where(owner_id: params[:user_id]).page(params[:page])
    else
      @events = Event.where(search_condition).page(params[:page])
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new_admin
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def register

  end

  def preview
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id] || params[:event_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:id, :description, :end_date, :is_paid, :price, :start_date, :status, :title, :owner_id)
  end

  def search_condition
    query = ''
    query += "start_date = '#{params[:start_date]}'" if params[:start_date].present?
    query += "AND end_date = '#{params[:end_date]}'" if params[:end_date].present?
    query += 'AND price >= '+params[:min_price] if params[:min_price].present?
    query += 'AND price <= '+params[:max_price] if params[:max_price].present?
    query
  end
end

app/views/events/_event.html.erb
<tr data-link="<%= event_path(event) %>">
  <td><%= event.id %></td>
  <td><%= event.title %></td>
  <td><%= event.start_date&.to_date %></td>
  <td><%= event.end_date&.to_date %></td>
  <td><%= true %></td>
  <td><%= event.status %></td>
</tr>

app/views/events/_events.html.erb
  <div class="box-header text-center">
    <h2 class="box-title m-10">LIST OF EVENTS
    <% if @user.present? %>
         <b>Created By <%= @user.fullname %></b>
    <% end %>
    </h2>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <%= render_search_and_new_btn(Event.filter_fields, events_path, new_event_path, 'Create New Event', false) %>
    <table id="dttb" class="table table-bordered table-hover">
      <thead>
      </tr>
      <tr>
        <th>No</th>
        <th>Title</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Price</th>
        <th>Status</th>
      </tr>
      </thead>
      <tbody>
      <%= render partial: :event, collection: @events %>
      <% if @events.blank? %>
      <tr><td colspan="5" class="text-red text-center"> There is no event for now!</td></tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate(@events, remote: true) %>
  </div>

app/views/events/_form.html.erb
<%= form_with(model: @event, local: true, class: 'form-horizontal event') do |f| %>
    <% if @event.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @event.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>
    <div class="box-body">
      <div class="col-md-6 col-xs-offset-2">

        <div class="form-group">
          <%= f.label :title, :class => 'col-sm-3 control-label' %>
          <div class="col-sm-9">
            <%= f.text_field :title, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :description, :class => 'col-sm-3 control-label' %>
          <div class="col-sm-9">
            <%= f.text_area :description, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :start_date, :class => 'col-sm-3 control-label' %>
          <div class="col-sm-9">
            <%= f.text_field :start_date, class: 'form-control datepicker' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :end_date, :class => 'col-sm-3 control-label' %>
          <div class="col-sm-9">
            <%= f.text_field :end_date, class: 'form-control datepicker' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :owner_id, :class => 'col-sm-3 control-label' %>
          <div class="col-sm-9">
            <%= f.select :owner_id, User.dropdown_options, {selected: @event.owner_id}, class: 'select2 form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :is_paid, :class => 'col-sm-3 control-label' %>
          <div class="col-sm-9">
            <%= f.check_box :is_paid, checked: @event.new_record? ? true : @event.is_paid? %>
          </div>
        </div>
        <div class="form-group price_container">
          <%= f.label :price, :class => 'col-sm-3 control-label' %>
          <div class="col-sm-9">
            <%= f.text_field :price, class: 'form-control' %>
          </div>
        </div>
      </div>
    </div>

    <div class=" box-footer">
      <div class="col-md-6 col-xs-offset-2 pull-right">
        <%= f.submit nil, :class => 'btn btn-info' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")), events_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>


<script>
  $(document).ready(function(){
      $('#event_is_paid').on('click', function(){
          $('.price_container').toggle(1300,'easeOutQuint');
      });
  });
</script>

app/views/events/edit.html.erb
<div class="box box-info">
  <div class="box-header with-border">
    <h3 class="box-title">Editing Event</h3>
  </div>
  <%=render 'form' %>
</div>

app/views/events/index.html.erb
<div class="home-main-content">
  <div class="box box-solid collapsed-box">
    <div class="box-header">
      <h3 class="box-title"></h3>
      <div class="box-tools pull-right">
        <button class="btn btn-primary btn-sm" data-widget="collapse"><i class="fa fa-search"></i>Search</button>
      </div>
    </div>
    <div style="display: none;" class="box-body">
      <%= form_with url: events_path, method: :get do |f| %>

          <div class="row">
            <div class="col-md-2">
              <div class="form-group">
                <%= f.label :start_date, :class => 'control-label' %>
                <%= f.text_field :start_date, class: 'form-control datepicker' %>
              </div>
            </div><!-- /.col -->
            <div class="col-md-2">
              <div class="form-group">
                <%= f.label :end_date, :class => 'control-label' %>
                <%= f.text_field :end_date, class: 'form-control datepicker' %>
              </div>
            </div><!-- /.col -->
            <div class="col-md-1">
              <div class="form-group">
                <%= f.label :min_price, :class => 'control-label' %>
                <%= f.text_field :min_price, class: 'form-control' %>
              </div>
            </div><!-- /.col -->
            <div class="col-md-2">
              <div class="form-group">
                <%= f.label :max_price, :class => 'control-label' %>
                <%= f.text_field :max_price, class: 'form-control' %>
              </div>
            </div><!-- /.col -->
            <div class="col-md-1">
              <div class="form-group">
                <label class="control-label">&nbsp;</label>
                <%= f.submit 'Filter', :class => 'btn btn-info' %>
              </div>
            </div><!-- /.col -->

          </div><!-- /.row -->
    <% end %>
    </div><!-- /.box-body -->
  </div><!-- /.box -->

  <div class="box">
    <div class="box-header text-center">
      <h2 class="box-title m-10">LIST OF EVENTS</h2>
    </div>



    <!-- /.box-header -->
    <div class="box-body">
      <%#= render_search_and_new_btn(Event.filter_fields, users_path, new_event_path, 'Create New Event', false) %>
      <table id="dttb" class="table table-bordered table-hover">
        <thead>
        </tr>
        <tr>
          <th>#</th>
          <th>Title</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th>Price</th>
          <th>Status</th>
        </tr>
        </thead>
        <tbody>
        <%= render partial: :event, collection: @events %>
        </tbody>
      </table>
      <%= paginate @events %>
    </div>
  </div>
</div>

app/views/events/index.js.erb
document.getElementById("user_detail_box").innerHTML = "<%= j render partial: 'events' %>"

app/views/events/new.html.erb
<div class="box box-info">
  <div class="box-header with-border">
    <h3 class="box-title">New Event</h3>
  </div>
  <%=render 'form' %>
</div>

app/views/events/preview.html.erb
<div class="invoice" style="border: 10px solid #f4f4f4">

  <div class="invoice">
    <div class="box box-info">
      <div class="box-header with-border text-center">
        <h3 class="box-title">Event Details</h3>
      </div>
      <div class='form-horizontal event'>
        <div class="row">
          <div class="col-md-4">
            <%= image_tag(@event.cover_image, style: "width: 100%") %>
          </div>
          <div class="col-md-8">
            <div class="table-responsive" style="margin-top: 20px;">
              <table class="table">
                <tbody>
                <tr>
                  <th style="width:25%">Title:</th>
                  <td><%= @event.title %></td>
                  <th>Description:</th>
                  <td><%= @event.description %></td>
                </tr>
                <tr>
                  <th>Start Date:</th>
                  <td><%= @event.start_date&.to_date %></td>
                  <th>End Date:</th>
                  <td><%= @event.end_date&.to_date %></td>
                </tr>
                <tr>
                  <th>Organizer:</th>
                  <td><%= @event.owner&.fullname %></td>
                </tr>
                </tbody>
              </table>
              <div id="app_links" style="margin-top: 10%; text-align: center">
                <div style="font-size: 22px; padding: 21px">You can install mobile app using following links.</div>
                <span>
                  <%= link_to "https://itunes.apple.com/us/app/profiler-life/id1251573847?mt=8" do %>
                   <%= image_tag('apple.png')%>
                  <% end %>
                </span>

                <span>
                  <%= link_to "https://play.google.com/store/apps/details?id=com.profilerlife.profiler" do %>
                      <%= image_tag('g.png')%>
                  <% end %>
                </span>
              </div>
            </div>
          </div>
        </div>


      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="box box-info">
  <div class="box-header with-border text-center">
    <h3 class="box-title">Event Details</h3>
  </div>
  <div class="box box-solid">
    <!-- /.box-header -->
    <div class="box-body">
      <div class="col-md-12">
        <div class="col-md-3">
          <label>Total Reviews / Total Attendees: </label>
          <div>
            <small class="label bg-blue" style="font-size: 15px;"><%= @event.reviews_count.to_s+"/"+@event.fetch_attendees.count.to_s %></small>
           </div>
        </div>
        <div class="col-md-3">
          <label>Reviewed As Occured:
            <small class="label bg-green"><%= @event.has_occured.count %></small>
          </label>
          <div class="progress progress-sm active">
            <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="<%= @event.reviews_count %>" aria-valuemin="0" aria-valuemax="<%= @event.reviews_count %>" style="width: <%= @event.has_occured_percent %>%">
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <label>Reviewed As Not Occured:
            <small class="label bg-red"><%= @event.has_not_occured.count %></small>
          </label>
          <div class="progress progress-sm">
            <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow="<%= @event.has_not_occured_percent %>" aria-valuemin="0" aria-valuemax="<%= @event.has_not_occured_percent %>" style="width: <%= @event.has_not_occured_percent %>%">
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <label>Not Reviewed:
            <small class="label progress-bar-warning"><%= @event.not_responded.count %></small>
          </label>
          <div class="progress progress-sm active">
            <div class="progress-bar progress-bar-warning progress-bar-striped" role="progressbar" aria-valuenow="<%= @event.not_responded_percent %>" aria-valuemin="0" aria-valuemax="<%= @event.not_responded_percent %>" style="width: <%= @event.not_responded_percent %>%">
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6 text-right">
        <button type="button" class="btn btn-primary" id="unlock_payment">Unlock Payment</button>
      </div>
      <% if @event.has_occured_percent < 60.0 %>
        <div class="col-md-6">
          <div class="alert alert-warning alert-dismissible" style="padding: 5px">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"  style="top: -8px; left: -1px;">×</button>
            <div><i class="icon fa fa-warning"></i>This event does't meat the criteria of minmum 60% positive reviews.
              </div>
          </div>
        </div>
      <% end %>

    </div>
    <!-- /.box-body -->
  </div>
  <div class='form-horizontal event'>
      <div class="box-body">
        <div class="col-md-12">

          <div class="col-md-6">
            <label class='control-label'> Title </label>
              <div class='form-control'><%= @event.title %></div>
          </div>
          <div class="col-md-6">
            <label class='control-label'> Description </label>
              <div class='form-control'><%= @event.description %></div>
          </div>

          <div class="col-md-6">
            <label class='control-label'> Start Date </label>
              <div class='form-control'><%= @event.start_date&.to_date %></div>
          </div>

          <div class="col-md-6">
            <label class='control-label'> End Date </label>
              <div class='form-control'><%= @event.end_date&.to_date %></div>
          </div>

          <div class="col-md-6">
            <label class='control-label'> Owner </label>
              <div class='form-control'><%= @event.owner&.fullname %></div>
          </div>
        </div>
      </div>

      <div class="box box-primary">
        <div class="box-header with-border text-center">
          <h3 class="box-title">Event Tickets Detail</h3>
        </div>
        <div class="box box-solid">
          <!-- /.box-header -->
          <div class="box-body">
            <table id="dttb" class="table table-bordered table-hover">
              <thead>
              </tr>
              <tr>
                <th>#</th>
                <th>Ticket Type</th>
                <th>Ticket Price</th>
                <th>Maximum Tickets</th>
                <th>Sold Tickets</th>
                <th>Available Tickets</th>
              </tr>
              </thead>
              <tbody>
              <% @event.ticket_packages.each_with_index do |packg, index| %>
                <tr>
                  <td><%= index+1 %></td>
                  <td><%= packg.ticket_type %></td>
                  <td>$ <%= packg.price %></td>
                  <td><%= packg.maximum_tickets %></td>
                  <td><%= packg.tickets.sold.count %></td>
                  <td><%= packg.tickets.available.count %></td>
                </tr>
               <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="box box-primary">
        <div class="box-header with-border text-center">
          <h3 class="box-title">Event Attendies</h3>
        </div>
        <div class="box box-solid">
          <!-- /.box-header -->
          <div class="box-body">
            <table id="dttbf" class="table table-bordered table-hover">
              <thead>
              </tr>
              <tr>
                <th>#</th>
                <th>User ID</th>
                <th>Name</th>
                <th>Email</th>
              </tr>
              </thead>
              <tbody>
              <% @event.user_attendees.each_with_index do |user, index|%>
                  <tr data-link="<%= user_path(user) %>">
                    <td><%=  index+1 %></td>
                    <td><%=  user.id %></td>
                    <td><%= user.fullname %></td>
                    <td><%= user.email %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class=" box-footer">
        <div class="col-md-6 col-xs-offset-2 pull-right hidden">
          <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_event_path(@event), :class => 'btn btn-info' %>
          <%= link_to t('.delete', :default => t("helpers.links.delete")), @event, method: :delete, :class => 'btn btn-danger', confirm: 'Are you sure?' %>
          <%= link_to t('.back', :default => t("helpers.links.back")), events_path, :class => 'btn btn-default' %>
        </div>
      </div>

  </div>
</div>