config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :passwords => 'passwords', confirmations: 'confirmations', sessions: "sessions"  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    root to: "devise/sessions#new"
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        member do
          put :update_password
          put :update_user_skills
          get :get_user_services
          get :get_user_availed_services
          post :add_working_days
          get :get_user_events
          put :add_stripe_token
          get :recent_payouts
          get :total_earning
          post :payout
          get :get_bank_info
          get :get_unreviewed_events
          get :user_event_reviews
          post :contact_as
          get :visitors
          get :notifications
          put :update_notification
          get :fetch_notifications
          get :vouchers
          get :verify_voucher
        end
        collection do
          put :forgot_password
          post :facebook_auth
          get :get_skilled_data
          get :search
        end
      end
      resources :sessions
      resources :service_categories
      resources :comments
      resources :appointments
      resources :endorsements do
        collection do
          put :un_endorse
        end
      end
      resources :user_connections do
        collection do
          get :get_connection_requests
          get :get_all_my_approved_connection_list
          get :get_connection_requests_new
          put :remove_connection
          get :connection_requests
        end
      end
      resources :working_days
      resources :reviews
      resources :services do
        member do
          get :check_available_slots_on
          get :service_reviews
        end
        collection do
          get :search
        end
      end
      resources :posts do
        member do
          post :like_post
          put  :share_post
          put  :repost
          get  :post_reactions
          post  :report_post
        end
        collection do

        end
      end
      resources :events do
        collection do
          get :search
        end
        member do
          get :get_attendees
          get :event_reviews
          post :charge_event
        end
      end
      resources :saved_events, only: [:create, :index] do
        collection do
          post :unsave
          get :services
        end
      end
      resources :tickets, only: [:index, :create, :show, :update]
      resources :messages, only: :create
      resources :chats, only: [:create, :index]
    end
  end

  resources :users
  resources :offers
  resources :home do
    collection do
      get :user_after_confirmation
      post :users_report
      post :posts_report
      post :services_report
      get :chat_room
    end
  end
  resources :categories
  resources :skills
  resources :sub_skills
  resources :events do
    collection do
      get :register
      get :preview
    end
  end
  resources :appointments
  resources :services do
    collection do
      get :preview
    end
  end
  resources :payments
  resources :outgoing_payments
  resources :charges do
    collection do
      post :charge_new_user_for_event
      get  :validate_tickets_count
    end
  end
  resources :posts
  resources :report_posts
  get  "registration" => "charges#registration"

  get '*path' => 'home#handle_no_rout'

  # mount ActionCable.server => '/cable'
end

app/models/outgoing_payment.rb
# == Schema Information
#
# Table name: outgoing_payments
#
#  id         :bigint           not null, primary key
#  amount     :float            default(0.0)
#  status     :integer          default(0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  event_id   :integer
#  user_id    :integer
#

class OutgoingPayment < ApplicationRecord

  ############ Associations ##############
  belongs_to :user
  belongs_to :event
  ############ Scopes ##############

  ############ Validations ##############


  def self.search(options = {})
    payments = OutgoingPayment.all
    payments = payments.where("user_id=?", options[:user]) if options[:user].present?
    payments = payments.where("event_id=?", options[:event]) if options[:event].present?
    payments = payments.where("created_at >= ?", options[:date_from]) if options[:date_from].present?
    payments = payments.where("created_at <= ?", options[:date_to]) if options[:date_to].present?
    payments
    payments
  end

end

app/controllers/outgoing_payments_controller.rb
class OutgoingPaymentsController < ApplicationController

  before_action :authenticate_user!, except: [:register]

  before_action :set_payment, only: [:show, :edit, :update, :destroy, :register]
  layout 'home', except: [:register]
  # GET /payments
  # GET /payments.json
  def index
    options = {
        # keyword: params[:keyword],
        user: params[:user],
        owner: params[:owner],
        event: params[:event],
        date_from: params[:from_date],
        date_to: params[:to_date]
    }
    @payments = OutgoingPayment.search(options).page(params[:page])
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new_admin
  def new
    @payment = OutgoingPayment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = OutgoingPayment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'OutgoingPayment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payments_path, notice: 'OutgoingPayment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'OutgoingPayment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def register

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = OutgoingPayment.find(params[:id] || params[:payment_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def payment_params
    params.require(:payment).permit(:id, :user_id, :amount, :created_at, :status)
  end

  def search_condition
    query = ''
    query += "start_date = '#{params[:start_date]}'" if params[:start_date].present?
    query += "AND end_date = '#{params[:end_date]}'" if params[:end_date].present?
    query += 'AND price >= '+params[:min_price] if params[:min_price].present?
    query += 'AND price <= '+params[:max_price] if params[:max_price].present?
    query
  end

end

app/views/outgoing_payments/_outgoing_payment.html.erb
<tr data-link="<%= event_path(outgoing_payment.event) %>">
  <td><%= outgoing_payment.id %></td>
  <td><%= outgoing_payment.event.try(:title) %></td>
  <td><%= outgoing_payment.user.try(:fullname) %></td>
  <td><%= outgoing_payment.amount/100 %></td>
  <td><button type="button" class="btn btn-success">Paid</button>
  <td><%= outgoing_payment.created_at.strftime('%B %d, %Y, %H:%M') %></td>
  </td>
</tr>

app/views/outgoing_payments/_outgoing_payments.html.erb
  <div class="box-header text-center">
    <h2 class="box-title m-10">LIST OF Outgoing Payments</h2>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <%#= render_search_and_new_btn(Event.filter_fields, events_path, new_event_path, 'Create New Event', false) %>
    <table id="dttb" class="table table-bordered table-hover">
      <thead>
      </tr>
      <tr>
        <th>No</th>
        <th>Event</th>
        <th>Organizer</th>
        <th>Amount</th>
        <th>Status</th>
        <th>Date</th>
      </tr>
      </thead>
      <tbody>
      <%= render partial: :outgoing_payment, collection: @payments %>
      </tbody>
    </table>
    <%= paginate(@payments, remote: true) %>
  </div>

app/views/outgoing_payments/_outgoing_payments_search_form.html.erb
<%= form_tag outgoing_payments_path, method: :get do %>

    <div class="col-md-12">
      <%#= render_search_and_new_btn(User.filter_fields, users_path, new_user_path, 'Create New User', false) %>
      <div class="form-group col-md-4">
        <label>Select Event</label>
        <%= select_tag "event", options_from_collection_for_select(Event.all, :id, :title, params[:event]), include_blank: "All", class: "form-control select2", style:"width: 100%;"%>
      </div>
      <div class="form-group col-md-4">
        <label>Select Organizer</label>
        <%= select_tag "user", options_from_collection_for_select(User.organizers, :id, :fullname, params[:user]), include_blank: "All", class: "form-control select2", style:"width: 100%;"%>
      </div>
      <div class="form-group col-md-2">
        <label>From Date</label>
        <%= text_field_tag "from_date", params[:from_date], class: "form-control datepicker", style:"width: 100%;", readonly: false %>
      </div>
      <div class="form-group col-md-2">
        <label>To Date</label>
        <%= text_field_tag "to_date", params[:to_date], class: "form-control datepicker", style:"width: 100%;", readonly: false %>
      </div>
    </div>

    <div class="form-group col-md-12 text-center">
      <%= submit_tag 'Apply Filters', class:"btn bg-olive btn-flat margin" %>
    </div>

    <div class="form-group col-md-12 text-center">
    </div>
<% end %>

app/views/outgoing_payments/index.html.erb
<div class="home-main-content">
  <div class="box">
    <!--<div class="box-header text-center">-->
    <!--<h2 class="box-title m-10">LIST OF USERS</h2>-->
    <!--</div>-->
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'outgoing_payments_search_form' %>
      </div>
    </div>
  </div>

  <div class="box">
    <div class="box-header text-center">
      <h2 class="box-title m-10">LIST OF Outgoing Payments</h2>
    </div>


    <!-- /.box-header -->
    <div class="box-body">
      <%#= render_search_and_new_btn(Event.filter_fields, users_path, new_event_path, 'Create New Event', false) %>
      <table id="dttb" class="table table-bordered table-hover">
        <thead>
        </tr>
        <tr>
          <th>No</th>
          <th>Event</th>
          <th>Organizer</th>
          <th>Amount</th>
          <th>Status</th>
          <th>Date</th>>
        </tr>
        </thead>
        <tbody>
        <%= render partial: :outgoing_payment, collection: @payments %>
        </tbody>
      </table>
      <%= paginate @payments %>
    </div>
  </div>
</div>

app/views/outgoing_payments/index.js.erb
document.getElementById("user_detail_box").innerHTML = "<%= j render partial: 'payments' %>"

app/views/outgoing_payments/show.html.erb
<div class="box box-info">
  <div class="box-header with-border">
    <h3 class="box-title">Payment Details</h3>
  </div>
  <div class='form-horizontal charge'>
    <div class="box-body">
      <div class="col-md-6 col-xs-offset-2">

        <div class="form-group">
          <label class='col-sm-3 control-label'> Amount </label>
          <div class="col-sm-9">
            <div class='form-control'><%= @payment.amount/100 %></div>
          </div>
        </div>
        <div class="form-group">
          <label class='col-sm-3 control-label'> Date </label>
          <div class="col-sm-9">
            <div class='form-control'><%= @payment.created_at %></div>
          </div>
        </div>
        <div class="form-group">
          <label class='col-sm-3 control-label'> Bank User </label>
          <div class="col-sm-9">
            <div class='form-control'><%= @payment.user&.fullname %></div>
          </div>
        </div>
      </div>
    </div>

    <div class=" box-footer">

    </div>

  </div>
</div>