config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :passwords => 'passwords', confirmations: 'confirmations', sessions: "sessions"  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    root to: "devise/sessions#new"
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        member do
          put :update_password
          put :update_user_skills
          get :get_user_services
          get :get_user_availed_services
          post :add_working_days
          get :get_user_events
          put :add_stripe_token
          get :recent_payouts
          get :total_earning
          post :payout
          get :get_bank_info
          get :get_unreviewed_events
          get :user_event_reviews
          post :contact_as
          get :visitors
          get :notifications
          put :update_notification
          get :fetch_notifications
          get :vouchers
          get :verify_voucher
        end
        collection do
          put :forgot_password
          post :facebook_auth
          get :get_skilled_data
          get :search
        end
      end
      resources :sessions
      resources :service_categories
      resources :comments
      resources :appointments
      resources :endorsements do
        collection do
          put :un_endorse
        end
      end
      resources :user_connections do
        collection do
          get :get_connection_requests
          get :get_all_my_approved_connection_list
          get :get_connection_requests_new
          put :remove_connection
          get :connection_requests
        end
      end
      resources :working_days
      resources :reviews
      resources :services do
        member do
          get :check_available_slots_on
          get :service_reviews
        end
        collection do
          get :search
        end
      end
      resources :posts do
        member do
          post :like_post
          put  :share_post
          put  :repost
          get  :post_reactions
          post  :report_post
        end
        collection do

        end
      end
      resources :events do
        collection do
          get :search
        end
        member do
          get :get_attendees
          get :event_reviews
          post :charge_event
        end
      end
      resources :saved_events, only: [:create, :index] do
        collection do
          post :unsave
          get :services
        end
      end
      resources :tickets, only: [:index, :create, :show, :update]
      resources :messages, only: :create
      resources :chats, only: [:create, :index]
    end
  end

  resources :users
  resources :offers
  resources :home do
    collection do
      get :user_after_confirmation
      post :users_report
      post :posts_report
      post :services_report
      get :chat_room
    end
  end
  resources :categories
  resources :skills
  resources :sub_skills
  resources :events do
    collection do
      get :register
      get :preview
    end
  end
  resources :appointments
  resources :services do
    collection do
      get :preview
    end
  end
  resources :payments
  resources :outgoing_payments
  resources :charges do
    collection do
      post :charge_new_user_for_event
      get  :validate_tickets_count
    end
  end
  resources :posts
  resources :report_posts
  get  "registration" => "charges#registration"

  get '*path' => 'home#handle_no_rout'

  # mount ActionCable.server => '/cable'
end

app/models/charge.rb
# == Schema Information
#
# Table name: charges
#
#  id              :bigint           not null, primary key
#  amount          :float
#  approved        :boolean          default(FALSE)
#  boolean         :boolean          default(FALSE)
#  company_share   :float
#  disputed        :boolean          default(FALSE)
#  refunded        :boolean          default(FALSE)
#  stripe_response :text
#  total_amount    :float
#  vc_amount       :float
#  vc_code         :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  event_id        :integer
#  owner_id        :integer
#  stripe_id       :string
#  user_id         :integer
#

class Charge < ApplicationRecord

  ############ Associations ##############
  belongs_to :owner, class_name: 'User'
  belongs_to :user
  belongs_to :event
  ############ Scopes ##############

  ############ Validations ##############

  def self.search(options = {})
    charges = Charge.all
    charges = charges.where("owner_id=?", options[:owner]) if options[:owner].present?
    charges = charges.where("user_id=?", options[:user]) if options[:user].present?
    charges = charges.where("event_id=?", options[:event]) if options[:event].present?
    charges = charges.where("created_at >= ?", options[:date_from]) if options[:date_from].present?
    charges = charges.where("created_at <= ?", options[:date_to]) if options[:date_to].present?
    charges
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  before_action :authenticate_user!, except: [:register, :validate_tickets_count, :charge_new_user_for_event, :registration]

  before_action :set_charge, only: [:show, :edit, :update, :destroy, :register]
  layout 'home', except: [:register]
  # GET /charges
  # GET /charges.json
  def index
    options = {
        # keyword: params[:keyword],
        user: params[:user],
        owner: params[:owner],
        event: params[:event],
        date_from: params[:from_date],
        date_to: params[:to_date]
    }
    @charges = Charge.search(options).page(params[:page])
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new_admin
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  def charge_new_user_for_event
    user, new_user = create_temp_user(params)
    if user.try(:id).present?
      event = Event.find(params[:event_id])
      user.update_columns(confirmed_at: nil, confirmation_token: SecureRandom.base64.tr('+/=', 'Qrt')) if new_user
      registration = Event.register_for_event(JSON.parse(params[:ticket_attributes][0]), user.id, event)
    end
    success = (user.try(:id).present? && registration[0].present?) ? true : false
    message = user.errors.present? ? user.errors.messages : nil
    if user.try(:id).present? && registration[0].present? && params[:amount].to_i > 0
      StripeCustomer.create_customer(params[:email], params[:stripeToken], user) if user.present?
      pars = params[:ticket_packages].map {|obj| YAML.load(obj)}
      new_params, event_params = {}, {}
      new_params['ticket_packages'] = pars[0]
      event_params['event'] = new_params
      response = StripeCustomer.new(user, params[:amount], event, event_params).web_charge
      unless response
      # remove all registered tickets
       registration[3].update_all(:owner_id=>nil)
       message = "Something went wrong with your payment, try again later."
       success = false
      end
    end

    if success
      EventMailer.event_registration(user, registration[0], registration[1], event, registration[2], registration[3], new_user).deliver
      # format.html { render :charge_new_user_for_event }
      respond_to do |format|
        format.html { redirect_to "/registration", notice: "Congrats: You have Successfully bought #{registration[0]} #{'ticket'.pluralize(registration[0])}" }
        format.json {render json: {message: "You have successfully bought #{registration[0]} #{'ticket'.pluralize(registration[0])}"}, status: :ok}
      end
    else
      respond_to do |format|
        format.html { redirect_back fallback_location: root_path, alert: message || "Something went wrong, try again later" }
        format.json { render :json => {:message => message || "Something went wrong, try again later"}, :status => :unprocessable_entity }
      end

    end

  end


  def validate_tickets_count
    event = Event.find(params[:event_id])
    unless validate_data
      render json: {error: @json}, status: :unprocessable_entity and return unless validate_data
    else
      render json: {is_free_event: event.is_free_event?, is_tax_by_creator: event.is_tax_by_creator}
    end
  end


  def create_temp_user(params)
    email = params[:email].present? ? params[:email].downcase : params[:stripeEmail].downcase
    first_name = params[:first_name].present? ? params[:first_name] : "Anonymous"
    last_name = params[:last_name].present? ? params[:last_name] : "User"
    user = User.find_by(email: email)
    new_user = false
    unless user.present?
      user = User.new(first_name: first_name, last_name: last_name, email: email, phone: params[:phone])
      user.password = user.password_confirmation = "pr3uis84"
      user.skip_confirmation!
      user.save
      new_user = SecureRandom.base64.tr('+/=', 'Qrt')[0,7]
    end
    return user, new_user
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to charges_path, notice: 'Charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  def registration
    render layout: false
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url, notice: 'Charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def register

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_charge
    @charge = Charge.find(params[:id] || params[:charge_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def charge_params
    params.require(:charge).permit(:id, :description, :end_date, :is_paid, :price, :start_date, :status, :title, :owner_id)
  end

  def search_condition
    query = ''
    query += "start_date = '#{params[:start_date]}'" if params[:start_date].present?
    query += "AND end_date = '#{params[:end_date]}'" if params[:end_date].present?
    query += 'AND price >= '+params[:min_price] if params[:min_price].present?
    query += 'AND price <= '+params[:max_price] if params[:max_price].present?
    query
  end

  def validate_data
    @json = ''
    JSON.parse(params[:ticket_attributes]).each do |attributes|
      ticket_package = TicketPackage.find_by(id: attributes["ticket_package_id"])
      available = ticket_package.available_tickets.eql?(0) ?  "No ticket" : "There are Only #{ticket_package.available_tickets} tickets"
      @json = available+" left for #{ticket_package.ticket_type} package." and return false if ticket_package.available_tickets < attributes["count"].to_i
    end
    true
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_charge.html.erb
<tr data-link="<%= charge_path(charge) %>">
  <td><%= charge.id %></td>
  <td><%= charge.user.try(:fullname) %></td>
  <td><%= charge.event.try(:title) %></td>
  <td><%= charge.owner.try(:fullname) %></td>
  <td><%= charge.amount/100 %></td>
  <td><%= charge.created_at.strftime('%B %d, %Y, %H:%M') %></td>
</tr>

app/views/charges/_charges.html.erb
  <div class="box-header text-center">
    <h2 class="box-title m-10">LIST OF charges</h2>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <%#= render_search_and_new_btn(Event.filter_fields, events_path, new_event_path, 'Create New Event', false) %>
    <table id="dttb" class="table table-bordered table-hover">
      <thead>
      </tr>
      <tr>
        <th>No</th>
        <th>Attendee</th>
        <th>Event</th>
        <th>Organizer</th>
        <th>Amount</th>
        <th>Date</th>
      </tr>
      </thead>
      <tbody>
      <%= render partial: :charge, collection: @charges %>
      </tbody>
    </table>
    <%= paginate(@charges, remote: true) %>
  </div>

app/views/charges/_charges_search_form.html.erb
<%= form_tag charges_path, method: :get do %>
    <div class="col-md-12">
      <%#= render_search_and_new_btn(User.filter_fields, users_path, new_user_path, 'Create New User', false) %>
      <div class="form-group col-md-2">
        <label>Select Attendee</label>
        <%= select_tag "user", options_from_collection_for_select(User.attendies, :id, :fullname, params[:user]), include_blank: "All", class: "form-control select2", style:"width: 100%;"%>
      </div>
      <div class="form-group col-md-4">
        <label>Select Event</label>
        <%= select_tag "event", options_from_collection_for_select(Event.all, :id, :title, params[:event]), include_blank: "All", class: "form-control select2", style:"width: 100%;"%>
      </div>
      <div class="form-group col-md-2">
        <label>Select Organizer</label>
        <%= select_tag "owner", options_from_collection_for_select(User.organizers, :id, :fullname, params[:owner]), include_blank: "All", class: "form-control select2", style:"width: 100%;"%>
      </div>
      <div class="form-group col-md-2">
        <label>From Date</label>
        <%= text_field_tag "from_date", params[:from_date], class: "form-control datepicker", style:"width: 100%;", readonly: false %>
      </div><div class="form-group col-md-2">
        <label>To Date</label>
        <%= text_field_tag "to_date", params[:to_date], class: "form-control datepicker", style:"width: 100%;", readonly: false %>
      </div>
    </div>

    <div class="form-group col-md-12 text-center">
      <%= submit_tag 'Apply Filters', class:"btn bg-olive btn-flat margin" %>
    </div>
<% end %>

app/views/charges/index.html.erb
<div class="home-main-content">
  <div class="box">
    <!--<div class="box-header text-center">-->
      <!--<h2 class="box-title m-10">LIST OF USERS</h2>-->
    <!--</div>-->
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'charges_search_form' %>
      </div>
    </div>
  </div>


  <div class="box">
    <div class="box-header text-center">
      <h2 class="box-title m-10">LIST OF charges</h2>
    </div>



    <!-- /.box-header -->
    <div class="box-body">
      <%#= render_search_and_new_btn(Event.filter_fields, users_path, new_event_path, 'Create New Event', false) %>
      <table id="dttb" class="table table-bordered table-hover">
        <thead>
        </tr>
        <tr>
          <th>No</th>
          <th>Attendee</th>
          <th>Event</th>
          <th>Organizer</th>
          <th>Amount</th>
          <th>Date</th>
        </tr>
        </thead>
        <tbody>
        <%= render partial: :charge, collection: @charges %>
        </tbody>
      </table>
      <%= paginate @charges %>
    </div>
  </div>
</div>

app/views/charges/index.js.erb
document.getElementById("user_detail_box").innerHTML = "<%= j render partial: 'charges' %>"

app/views/charges/registration.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Event Registration</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
    .rails-default-error-page {
      background-color: #EFEFEF;
      color: #2E2F30;
      text-align: center;
      font-family: arial, sans-serif;
      margin: 0;
    }

    .rails-default-error-page div.dialog {
      width: 95%;
      max-width: 33em;
      margin: 4em auto 0;
    }

    .rails-default-error-page div.dialog > div {
      border: 1px solid #CCC;
      border-right-color: #999;
      border-left-color: #999;
      border-bottom-color: #BBB;
      border-top: #3767b0 solid 4px;
      border-top-left-radius: 9px;
      border-top-right-radius: 9px;
      background-color: white;
      padding: 7px 12% 0;
      box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
    }

    .rails-default-error-page h1 {
      font-size: 100%;
      color: #3767b0;
      line-height: 1.5em;
    }

    .rails-default-error-page div.dialog > p {
      margin: 0 0 1em;
      padding: 1em;
      background-color: #F7F7F7;
      border: 1px solid #CCC;
      border-right-color: #999;
      border-left-color: #999;
      border-bottom-color: #999;
      border-bottom-left-radius: 4px;
      border-bottom-right-radius: 4px;
      border-top-color: #DADADA;
      color: #666;
      box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
    }
  </style>
</head>

<body class="rails-default-error-page">
<!-- This file lives in public/404.html -->
<div class="dialog">
  <div>
    <h1>
      <% if notice %>
        <%= notice %>
      <% end %>
    </h1>
  </div>
  <p></p>
</div>
</body>
</html>

app/views/charges/show.html.erb
<div class="box box-info">
  <div class="box-header with-border">
    <h3 class="box-title">charge Details</h3>
  </div>
  <div class='form-horizontal charge'>
      <div class="box-body">
        <div class="col-md-6 col-xs-offset-2">

          <div class="form-group">
            <label class='col-sm-3 control-label'> Amount </label>
            <div class="col-sm-9">
              <div class='form-control'><%= @charge.amount/100 %></div>
            </div>
          </div>
          <div class="form-group">
            <label class='col-sm-3 control-label'> Date </label>
            <div class="col-sm-9">
              <div class='form-control'><%= @charge.created_at %></div>
            </div>
          </div>
          <div class="form-group">
            <label class='col-sm-3 control-label'> Charged User </label>
            <div class="col-sm-9">
              <div class='form-control'><%= @charge.user&.fullname %></div>
            </div>
          </div>
        </div>
      </div>

      <div class=" box-footer">

      </div>

  </div>
</div>